# Generated by Django 2.2.4 on 2019-09-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_name', models.CharField(max_length=100)),
                ('draft_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_abbreviation', models.CharField(max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=10)),
                ('informational', models.BooleanField(blank=True, default=False)),
                ('discard', models.BooleanField(blank=True, default=False)),
                ('mapped_scoring_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.ScoringCategory')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Projection')),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='scoring_categories',
            field=models.ManyToManyField(blank=True, to='draft.ScoringCategory'),
        ),
    ]
