# Generated by Django 2.2.4 on 2019-09-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=10)),
                ('informational', models.BooleanField(null=True)),
                ('discard', models.BooleanField(null=True)),
                ('mapped_scoring_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.ScoringCategory')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Projection')),
            ],
        ),
    ]
