# Generated by Django 2.2.4 on 2019-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_scoringcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
