# Generated by Django 2.2.4 on 2019-08-31 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0004_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draft_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoringcategory',
            name='drafts',
            field=models.ManyToManyField(to='draft.Draft'),
        ),
    ]
