# Generated by Django 2.2.4 on 2019-09-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20190831_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcategory',
            name='drafts',
        ),
        migrations.AddField(
            model_name='draft',
            name='scoring_categories',
            field=models.ManyToManyField(blank=True, to='draft.ScoringCategory'),
        ),
    ]
