# Generated by Django 2.2.4 on 2019-09-01 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20190901_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='draft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='draft.Draft'),
            preserve_default=False,
        ),
    ]
